### PR TITLE
Added  VictorKalininskiy-Bug_report  folder

### PR DESCRIPTION
**Pull request by VictorK2018**
Added  my Bug report  folder.

### CODE REVIEW

**Review by TatsianaLentz — APPROVED** [review]
LGTM!

**Comment by AlBuyan** [comment]
Good!

**Comment by Nazira489** [comment]
LGTM!

**Review by Nazira489 — APPROVED** [review]

**Review by DanillKo — APPROVED** [review]
Good!

**Review by Nazira489 — APPROVED** [review]

**Review by AlBuyan — APPROVED** [review]

**Pull request merged**
